name: scarla
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text:
  built_collection: ^5.0.0-nullsafety.0
  built_value: ^8.0.0-nullsafety.0
  cached_network_image: 2.5.1
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  font_awesome_flutter:
  google_fonts:
  google_sign_in: ^4.0.16
  image_picker: ^0.6.7+22
  mime_type: ^1.0.0
  rxdart: ^0.25.0
  sign_in_with_apple: ^2.5.4
  url_launcher:
  youtube_player_flutter: ^7.0.0+7
  flutter_colorpicker: ^0.4.0
  imgur: ^1.1.1
  page_transition: ^1.1.7+6
  chewie: ^1.0.0
  wave: ^0.2.0
  selectable_circle: ^0.1.6+4
  animated_icon_button: ^1.0.0
  flutter_icons: ^1.1.0
  lottie: ^0.7.0+1
  flutter_native_splash: ^0.3.2
  loading_indicator: ^2.0.1
  frino_icons: ^1.0.1+4
  fluentui_system_icons: ^1.1.122
  line_icons: ^2.0.1
  flutter_launcher_icons: ^0.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  image: ^3.0.0-nullsafety.0
  yaml: ^3.0.0-nullsafety.0
  xml: ^5.0.0
  archive: ^2.0.0
  args: ^1.4.0

dev_dependencies:
  build_runner: ^1.11.0
  built_value_generator: ^8.0.0-nullsafety.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/games/icons/
    - assets/games/cards/lol/
    - assets/games/cards/mw/
    - assets/games/cards/ow/
    - assets/games/cards/rl/
    - assets/games/cards/valorant/
    - assets/games/ranks/lol/
    - assets/games/ranks/ow/
    - assets/games/ranks/mw/
    - assets/games/ranks/rl/
    - assets/games/ranks/valorant/
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
